"""empty message

Revision ID: 54061d55e880
Revises: b8f3f5f21704
Create Date: 2023-08-01 13:07:45.503368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54061d55e880'
down_revision = 'b8f3f5f21704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('mass')

    # ### end Alembic commands ###
