"""empty message

Revision ID: b8f3f5f21704
Revises: 2dbdb86e18b7
Create Date: 2023-08-01 13:06:59.602342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f3f5f21704'
down_revision = '2dbdb86e18b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('height', sa.String(length=150), nullable=True),
    sa.Column('hair_color', sa.String(length=150), nullable=True),
    sa.Column('skin_color', sa.String(length=150), nullable=True),
    sa.Column('eye_color', sa.String(length=150), nullable=True),
    sa.Column('birth_year', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=150), nullable=True),
    sa.Column('homeworld', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
